name: "sld docker compose"
on: [pull_request, push]

jobs:
  docker-compose-sld:
    runs-on: ubuntu-latest
    container: 
    steps:
      - uses: actions/checkout@main
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  repository: D10S0VSkY-OSS/Stack-Lifecycle-Deployment
        #  path: './poc01'
      - name: Testing0
        run: |
          pwd
          ls -ltr
      - name: Testing1
        run: |
          docker-compose up -d
          docker ps
          docker network ls
          ss -putan
          ip add sh
      - name: Testing2
        run: |
          IP=$(ip add sh|grep eth0|grep inet|awk '{print $2}'|cut -d '/' -f 1)
          curl -s --retry 10 --retry-connrefused http://$IP:8080
      - name: Testing3
        run: |
          bash ./init.sh