name: "sld docker compose"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: D10S0VSkY-OSS/Stack-Lifecycle-Deployment
          path: './poc01'
      - name: Testing0
        run: |
          pwd
          ls -ltr
      - name: Testing1
        run: |
          cd ./poc01/play-with-sld/docker
          docker-compose up -d
      - name: Testing2
        run: |
          docker ps
          sh play.sh init
          cd ../../sld-api-backend/
          pwd
          curl -X 'POST' \
            'http://api-backend:8000/api/v1/authenticate/access-token-json' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{
            "username": "admin",
            "password": "Password08@"}'

         