name: "sld docker compose"
on: [pull_request, push]

jobs:
  docker-compose-sld:
    runs-on: ubuntu-latest
    container: redis 
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: D10S0VSkY-OSS/Stack-Lifecycle-Deployment
          path: './poc01'
      - name: Testing0
        run: |
          pwd
          ls -ltr
      - name: Testing1
        run: |
          docker ps
          cd ./poc01/play-with-sld/docker
          pwd
          sh play.sh init
          cd ../../sld-api-backend/
          pwd
          ss -putan
          sudo apt-get install curl jq -y
          docker network ls
          curl 0.0.0.0:6379