name: "sld docker compose"
on: [pull_request, push]

jobs:
  docker-compose-sld:
    runs-on: ubuntu-latest
    container: 
    steps:
      - uses: actions/checkout@main
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  repository: D10S0VSkY-OSS/Stack-Lifecycle-Deployment
        #  path: './poc01'
      - name: Testing0
        run: |
          pwd
          ls -ltr
      - name: Testing2
        run: |
          docker-compose up -d
          docker ps
          ss -putan
      - name: Testing2
        run: |
          pwd
          docker-compose up curl
          docker run --network container:api-backend dwdraju/alpine-curl-jq curl  --retry 10 --retry-connrefused http://localhost:8000/