name: "sld docker compose"
on: [pull_request, push]

jobs:
  docker-compose-sld:
    runs-on: ubuntu-latest
    container: 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: D10S0VSkY-OSS/Stack-Lifecycle-Deployment
          path: './poc01'
      - name: Testing0
        run: |
          pwd
          ls -ltr
      - name: Testing1
        run: |
          ls -ltr
          pwd
          docker-compose up -d
      - name: Testing2
        run: |
          docker ps
          ss -putan