name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: engineerd/setup-kind@v0.5.0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: D10S0VSkY-OSS/Stack-Lifecycle-Deployment
          path: './poc01'
      - name: Testing
        run: |
          pwd
          ls -ltr
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kubectl apply -k ./poc01/play-with-sld/kubernetes/k8s
          kubectl wait --for=condition=ready pod -l app="stack-lifecycle-deploy" --timeout=3600s
          kubectl get pods 