name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: engineerd/setup-kind@v0.5.0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: D10S0VSkY-OSS/Stack-Lifecycle-Deployment
          path: './poc01'
      - name: Testing0
        run: |
          pwd
          ls -ltr
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Testing1
        run: |
          cd ./poc01/play-with-sld/docker
          docker-compose up -d
      - name: Testing2
        run: |
          docker ps
         